app = "digit-classifier-tensorboard"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  HOST = "0.0.0.0"
  PORT = "6006"
  TENSORBOARD_BIND_ALL = "true"

[http_service]
  internal_port = 6006
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "get"
  path = "/"
  protocol = "http"
  timeout = "10s"
  tls_skip_verify = false

[mounts]
  source = "tensorboard_data"
  destination = "/app/logs"

# Specify machine size
[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1 